//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Date &quot;1993/07/09&quot;]
        ///[Event &quot;Kisei-sen&quot;]
        ///[Opening &quot;Yagura&quot;]
        ///[Black &quot;Habu Yoshiharu&quot;]
        ///[White &quot;Tanigawa Koji&quot;]
        ///1.P7f 	2.P8d 	3.G7h 	4.G3b 	5.S6h 	6.P3d 
        ///7.P6f 	8.S6b 	9.P5f 	10.P5d 	11.S4h 	12.S4b 
        ///13.G5h 	14.K4a 	15.K6i 	16.G5b 	17.G56g 	18.S3c 
        ///19.S7g 	20.B3a 	21.B7i 	22.P4d 	23.P3f 	24.P7d 
        ///25.B6h 	26.G54c 	27.K7i 	28.P8e 	29.R3h 	30.B6d 
        ///31.N3g 	32.K3a 	33.P2f 	34.K2b 	35.P1f 	36.P1d 
        ///37.K8h 	38.S5c 	39.L1g 	40.P5e 	41.P6e 	42.B7c 
        ///43.P5e 	44.P6d 	45.S5g 	46.P6e 	47.S5f 	48.R6b 
        ///49.N2e 	50.S2d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Game1_psn {
            get {
                return ResourceManager.GetString("Game1.psn", resourceCulture);
            }
        }
    }
}
