//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShogiCore.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShogiCore.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] _16th_Kio_Match {
            get {
                object obj = ResourceManager.GetObject("_16th_Kio_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _20th_Osho_Match {
            get {
                object obj = ResourceManager.GetObject("_20th_Osho_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _25_0102 {
            get {
                object obj = ResourceManager.GetObject("_25_0102", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _26th_Osho_Match {
            get {
                object obj = ResourceManager.GetObject("_26th_Osho_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _29th_Osho_Match {
            get {
                object obj = ResourceManager.GetObject("_29th_Osho_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _31st_Meijin_Match {
            get {
                object obj = ResourceManager.GetObject("_31st_Meijin_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _31st_Oi_Match {
            get {
                object obj = ResourceManager.GetObject("_31st_Oi_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _32nd_Oi_Match {
            get {
                object obj = ResourceManager.GetObject("_32nd_Oi_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _32nd_Osho_Match {
            get {
                object obj = ResourceManager.GetObject("_32nd_Osho_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _33rd_Meijin_Match {
            get {
                object obj = ResourceManager.GetObject("_33rd_Meijin_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _38th_Oza_Match {
            get {
                object obj = ResourceManager.GetObject("_38th_Oza_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _39th_Oza_Match {
            get {
                object obj = ResourceManager.GetObject("_39th_Oza_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _3rd_RyuO_Match {
            get {
                object obj = ResourceManager.GetObject("_3rd_RyuO_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _40th_Osho_Match {
            get {
                object obj = ResourceManager.GetObject("_40th_Osho_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _48th_Meijin_Match {
            get {
                object obj = ResourceManager.GetObject("_48th_Meijin_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _49th_Meijin_Match {
            get {
                object obj = ResourceManager.GetObject("_49th_Meijin_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _4th_RyuO_Match {
            get {
                object obj = ResourceManager.GetObject("_4th_RyuO_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _56th_Kisei_Match {
            get {
                object obj = ResourceManager.GetObject("_56th_Kisei_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _57th_Kisei_Match {
            get {
                object obj = ResourceManager.GetObject("_57th_Kisei_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _58th_Kisei_Match {
            get {
                object obj = ResourceManager.GetObject("_58th_Kisei_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _59th_Kisei_Match {
            get {
                object obj = ResourceManager.GetObject("_59th_Kisei_Match", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Jan_Jun1992 {
            get {
                object obj = ResourceManager.GetObject("Jan_Jun1992", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] misc_pro_games {
            get {
                object obj = ResourceManager.GetObject("misc_pro_games", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
