//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShogiCore.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShogiCore.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name &quot;Matt Casters&quot;]
        ///[Email &quot;matt@impakt.be&quot;]
        ///[Country &quot;Japan&quot;]
        ///[Sente &quot;Minami Yoshikazu&quot;]
        ///[Gote &quot;Habu Yohsiharu&quot;]
        ///[Black_grade &quot;Kio&quot;]
        ///[White_grade &quot;6dan&quot;]
        ///[Result &quot;0-1&quot;]
        ///[Comment &quot;Originaly entered by Reijger Grimbergen&quot;]
        ///[Source &quot;Shogi-L Game Archives&quot;]
        ///[Event &quot;16th  Kio Title Match 1991&quot;]
        ///[Date &quot;19910115&quot;]
        ///[Round &quot;1&quot;]
        ///[Venue &quot; &quot;]
        ///[Proam &quot;Professional&quot;]
        ///P7g-7f P8c-8d S7i-6h P3c-3d P6g-6f S7a-6b P5g-5f P5c-5d S3i-4h S3a-4b G4i-5h G4a-3b G5h-6g K5a-4a S6h-7g P7c-7d P2g-2f G6a-5b P2f-2e S4b-3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _16th_Kio_Match {
            get {
                return ResourceManager.GetString("_16th_Kio_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sente &quot;Oyama Yasuharu&quot;]
        ///[SenteGrade &quot;Challenger&quot;]
        ///[Gote &quot;Nakahara Makoto&quot;]
        ///[GoteGrade &quot;10 Dan&quot;]
        ///[Date &quot;1971/01/19&quot;]
        ///[Event &quot;20th Osho sen&quot;]
        ///[Round &quot;1&quot;]
        ///[Result &quot;1-0&quot;]
        ///[Moves &quot;147&quot;]
        ///1.P7f P8d 2.P5f P5d 3.S6h P3d 4.P6f S6b 5.R5h K4b 6.K4h K3b 7.K3h P1d 8.P1f G65b 9.K2h S4b 10.S3h P7d 11.S6g S45c 12.G7h P6d 13.P4f R7b 14.P3f G44b 15.S4g P7e 16.xP xR 17.R3h S4d 18.G6h S6c 19.G5g R7b 20.P*7f P8e 21.B7g S7d 22.P4e S5c 23.P3e xP 24.xR P*3c 25.R3h P*7e 26.S4f Px7f 27.xS S7e 28.S6g P8f 29.xP xS 30.xB R7i+  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _20th_Osho_Match {
            get {
                return ResourceManager.GetString("_20th_Osho_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始日時：2002/03/16
        ///棋戦：第25回朝日アマ名人戦全国大会
        ///戦型：横歩取り
        ///場所：都ホテル東京
        ///掲載：３番勝負への道
        ///先手：小林庸俊（北関東）
        ///後手：今村計二（中国）
        ///
        ///▲７六歩    △３四歩    ▲２六歩    △８四歩    ▲２五歩    △８五歩
        ///▲７八金    △３二金    ▲２四歩    △同　歩    ▲同　飛    △８六歩
        ///▲同　歩    △同　飛    ▲３四飛    △８八角成  ▲同　銀    △２八歩
        ///▲同　銀    △４五角    ▲２四飛    △２三歩    ▲７七角    △８八飛成
        ///▲同　角    △２四歩    ▲１一角成  △３三桂    ▲３六香    △６六銀
        ///▲３三香成  △６七銀不成▲７九金    △７八銀不成▲同　金    △同角成
        ///▲３二成香  △６八飛    ▲５八金打  △６九飛成  ▲４八玉    △３二銀
        ///▲６二歩    △同　玉    ▲６四歩    △同　龍    ▲４二飛    △５二香
        ///▲３二飛成  △８九馬    ▲６七歩    △５五桂    ▲５六銀    △９九馬
        ///▲６六桂    △４ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _25_0102 {
            get {
                return ResourceManager.GetString("_25_0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sente &quot;Oyama Yasuharu&quot;]
        ///[SenteGrade &quot;Kisei&quot;]
        ///[Gote &quot;Nakahara Makoto&quot;]
        ///[GoteGrade &quot;9 Dan&quot;]
        ///[Date &quot;1976/01/18&quot;]
        ///[Event &quot;26th Osho sen&quot;]
        ///[Round &quot;1&quot;]
        ///[Result &quot;0-1&quot;]
        ///[Moves &quot;114&quot;]
        ///1.P7f P8d 2.R7h P3d 3.P6f P8e 4.B7g S6b 5.S6h K4b 6.K4h K3b 7.K3h G65b 8.K2h P1d 9.P1f P5d 10.S3h S4b 11.G65h S45c 12.P5f P7d 13.P4f G44b 14.P3f P9d 15.G4g S6d 16.S6g P7e 17.N3g Px7f 18.xS R7b 19.B8h S6e 20.S6g S7d 21.P4e S7e 22.B7i P*7f 23.B4f P6d 24.P5e xP 25.R5h S6c 26.Bx5e xB 27.xR P*5d 28.R5h P8f 29.xP R8b 30.S7h Rx8f 31 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _26th_Osho_Match {
            get {
                return ResourceManager.GetString("_26th_Osho_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sente &quot;Nakahara Makoto&quot;]
        ///[SenteGrade &quot;Meijin&quot;]
        ///[Gote &quot;Oyama Yasuharu&quot;]
        ///[GoteGrade &quot;9 Dan&quot;]
        ///[Date &quot;1979/10/19&quot;]
        ///[Event &quot;29th Osho sen&quot;]
        ///[Round &quot;1&quot;]
        ///[Result &quot;0-1&quot;]
        ///[Moves &quot;228&quot;]
        ///1.P7f P3d 2.P2f P4d 3.S4h S3b 4.P5f R4b 5.K6h K6b 6.K7h S7b 7.G45h K7a 8.P9f P9d 9.S6h S4c 10.S45g P6d 11.P7e S5d 12.S7g P8d 13.S56f P4e 14.P2e B3c 15.P5e S56c 16.R2f G45b 17.S7f K8b 18.P8f S8c 19.B7g G7b 20.K8h P7d 21.xP xS6 22.P*7e S6c 23.G7h N7c 24.G56h G4c 25.L9h G4d 26.R5f P6e 27.xS6 xN 28.xS S*6d 29.S7f P*7d 30.N*8g P4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _29th_Osho_Match {
            get {
                return ResourceManager.GetString("_29th_Osho_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sente &quot;Oyama Yasuharu&quot;]
        ///[SenteGrade &quot;Meijin&quot;]
        ///[Gote &quot;Nakahara Makoto&quot;]
        ///[GoteGrade &quot;10 Dan&quot;]
        ///[Date &quot;1972/04/08&quot;]
        ///[Event &quot;31st Meijin sen&quot;]
        ///[Round &quot;1&quot;]
        ///[Result &quot;0-1&quot;]
        ///[Moves &quot;112&quot;]
        ///1.P7f P8d 2.R7h S6b 3.S6h K4b 4.P7e P6d 5.P6f P8e 6.B7g K3b 7.S6g P3d 8.K4h P1d 9.P1f G65b 10.S7f S6c 11.K3h P7d 12.xP xS 13.P*7e S6c 14.G65h R8d 15.K2h P9d 16.S3h S5d 17.P5f N7c 18.G6g P9e 19.R5h G54b 20.P2f B3c 21.P3f K2b 22.S2g S3b 23.G3h P6e 24.R6h B4d 25.N3g P2d 26.Px6e P8f 27.xP Nx6e 28.Bx4d xP 29.P8e P*6f 30.xG N5g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _31st_Meijin_Match {
            get {
                return ResourceManager.GetString("_31st_Meijin_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sente &quot;Tanigawa Koji&quot;]
        ///[SenteGrade &quot;Oi&quot;]
        ///[Gote &quot;Sato Yasumitsu&quot;]
        ///[GoteGrade &quot;5 Dan&quot;]
        ///[Date &quot;1990/07/12&quot;]
        ///[Event &quot;31st Oi sen&quot;]
        ///[Round &quot;1&quot;]
        ///[Result &quot;0-1&quot;]
        ///[Moves &quot;82&quot;]
        ///1.P2f P8d 2.P2e P8e 3.G7h G3b 4.P2d xP 5.xR P*2c 6.R2f S7b 7.P1f P1d 8.S3h P6d 9.P7f P8f 10.xP xR 11.P*8g R8b 12.P3f P3d 13.S3g S6c 14.P3e xP 15.S4f S5d 16.K5h Bx8h+ 17.xS S2b 18.P*3d G5b 19.G3h P4d 20.P7e K4b 21.Sx3e S4c 22.N7g P*3c 23.xP+ xS 24.P7d xP 25.P*7b xR 26.B*8c R7c 27.B6a+ G5a 28.N8e Gx6a 29.Nx7c+ xN 30.R*8a S5b 31.Rx9a+ N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _31st_Oi_Match {
            get {
                return ResourceManager.GetString("_31st_Oi_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name &quot;Matt Casters&quot;]
        ///[Email &quot;matt@netpoint.be&quot;]
        ///[Country &quot;Japan&quot;]
        ///[Sente &quot;Tanigawa Koji&quot;]
        ///[Gote &quot;Nakada Hiyoki&quot;]
        ///[Black_grade &quot;Oi&quot;]
        ///[White_grade &quot;Chall&quot;]
        ///[Result &quot; &quot;]
        ///[Comment &quot;Original filename : 32oi1.txt&quot;]
        ///[Source &quot;Reijer Grimbergen&quot;]
        ///[Event &quot;32nd Oi Title Match&quot;]
        ///[Date &quot;19910711&quot;]
        ///[Round &quot;1&quot;]
        ///[Venue &quot; &quot;]
        ///[Proam &quot;Professional&quot;]
        ///P7g-7f P8c-8d S7i-6h P3c-3d S6h-7g S7a-6b S3i-4h S3a-4b P5g-5f P5c-5d G4i-5h G4a-3b P6g-6f K5a-4a G5h-6g P7c-7d G6i-7h G6a-5b K5i-6i S4b-3c B8h-7i B2b-3a B7i-6h P9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _32nd_Oi_Match {
            get {
                return ResourceManager.GetString("_32nd_Oi_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sente &quot;Oyama Yasuharu&quot;]
        ///[SenteGrade &quot;Challenger&quot;]
        ///[Gote &quot;Nakahara Makoto&quot;]
        ///[GoteGrade &quot;Meijin&quot;]
        ///[Date &quot;1973/01/17&quot;]
        ///[Event &quot;22nd Osho sen&quot;]
        ///[Round &quot;1&quot;]
        ///[Result &quot;0-1&quot;]
        ///[Moves &quot;100&quot;]
        ///1.P7f P8d 2.S7h P3d 3.P6f S6b 4.R6h K4b 5.K4h K3b 6.K3h P5d 7.K2h P1d 8.P1f G65b 9.S3h S5c 10.P5f B1c 11.R5h B2d 12.S6g P4d 13.P5e xP 14.xR G4c 15.R5i K2b 16.G7h S3b 17.S5f P6d 18.P2f P7d 19.P4f P8e 20.B7g P7e 21.xP Bx4f 22.P6e P8f 23.xP P*8h 24.Px6d xS 25.S54g B2d 26.P2e B3c 27.Bx8h Rx8f 28.P*6c P*6g 29.B7g R2f 30.S2g  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _32nd_Osho_Match {
            get {
                return ResourceManager.GetString("_32nd_Osho_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name &quot;Majewski Thomas&quot;]
        ///[Country &quot;Japan&quot;]
        ///[Sente &quot;Oyama Yasuharu&quot;]
        ///[Gote &quot;Nakahara Makoto&quot;]
        ///[Black_grade &quot;10 Dan&quot;]
        ///[White_grade &quot;Meijin&quot;]
        ///[Result &quot;1-0&quot;]
        ///[Opening &quot;Sangenbisha&quot;]
        ///[Source &quot;Oyama&apos;s gamescore&quot;]
        ///[Event &quot;33rd Meijin sen Title Match&quot;]
        ///[Round &quot;1&quot;]
        ///[Proam &quot;Professional&quot;]
        ///P7g-7f P8c-8d R2h-7h P3c-3d P6g-6f S7a-6b S7i-6h K5a-4b K5i-4h K4b-3b K4h-3h P1c-1d P1g-1f P5c-5d P7f-7e S3a-4b S6h-6g P4c-4d G6i-5h S4b-4c P4g-4f S6b-5c P9g-9f P3d-3e K3h-2h P8d-8e B8h-9g P6c-6d P7e-7d P7cx7d R7hx7d G6a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _33rd_Meijin_Match {
            get {
                return ResourceManager.GetString("_33rd_Meijin_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name &quot;Matt Casters&quot;]
        ///[Email &quot;matt@netpoint.be&quot;]
        ///[Country &quot;Japan&quot;]
        ///[Sente &quot;Nakahara Makoto&quot;]
        ///[Gote &quot;Tanigawa Koji&quot;]
        ///[Black_grade &quot;Oza&quot;]
        ///[White_grade &quot;Oi&quot;]
        ///[Result &quot; &quot;]
        ///[Comment &quot;Original filename : 38oza1.txt&quot;]
        ///[Source &quot;Reijer Grimbergen&quot;]
        ///[Event &quot;38th Oza Title Match&quot;]
        ///[Date &quot;19900909&quot;]
        ///[Round &quot;1&quot;]
        ///[Venue &quot; &quot;]
        ///[Proam &quot;Professional&quot;]
        ///P2g-2f P8c-8d P2f-2e P8d-8e G6i-7h G4a-3b P2e-2d P2cx2d R2hx2d P*2c R2d-2f S7a-7b P1g-1f P1c-1d S3i-3h P3c-3d K5i-5h P9c-9d P3g-3f B2b-4d P3f-3e B4dx3e R2f-5f S3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _38th_Oza_Match {
            get {
                return ResourceManager.GetString("_38th_Oza_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name &quot;Matt Casters&quot;]
        ///[Email &quot;matt@netpoint.be&quot;]
        ///[Country &quot;Japan&quot;]
        ///[Sente &quot;Fukuzaki Bungo&quot;]
        ///[Gote &quot;Tanigawa Koji&quot;]
        ///[Black_grade &quot;Chall&quot;]
        ///[White_grade &quot;Oza&quot;]
        ///[Result &quot; &quot;]
        ///[Comment &quot;Original filename : 39oza1.txt&quot;]
        ///[Source &quot;Reijer Grimbergen&quot;]
        ///[Event &quot;39th Oza Title Match&quot;]
        ///[Date &quot;19910903&quot;]
        ///[Round &quot;1&quot;]
        ///[Venue &quot; &quot;]
        ///[Proam &quot;Professional&quot;]
        ///P7g-7f P8c-8d P5g-5f P8d-8e B8h-7g P5c-5d R2h-8h P3c-3d S7i-6h S7a-6b K5i-4h P7c-7d P6g-6f K5a-4b K4h-3h K4b-3b K3h-2h G6a-5b G6i-5h S6b-5c S6h-5g B2b-3c L1i-1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _39th_Oza_Match {
            get {
                return ResourceManager.GetString("_39th_Oza_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sente &quot;Tanigawa Koji&quot;]
        ///[SenteGrade &quot;Oi, Oza&quot;]
        ///[Gote &quot;Habu Yoshiharu&quot;]
        ///[GoteGrade &quot;RyuO&quot;]
        ///[Date &quot;1990/10/19&quot;]
        ///[Event &quot;3rd RyuO sen&quot;]
        ///[Round &quot;1&quot;]
        ///[Result &quot;1-0&quot;]
        ///[Moves &quot;111&quot;]
        ///{ From &lt;http://www.shogi.net/arc/games/ryu-o.match-90&gt;
        ///
        ///Below follows the complete annotated RyuO sen 1990 between Tanigawa Koji (challenger, Oi, Oza) and Habu Yoshiharu (Ryu O). Comment by Murooka Katsuhiko, 5-dan professional. Compiled by Pieter Stouten.
        ///
        ///Detailed results:
        ///Game 1, 19 and 20 October:       Tanigawa Koji - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3rd_RyuO_Match {
            get {
                return ResourceManager.GetString("_3rd_RyuO_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name &quot;Matt Casters&quot;]
        ///[Email &quot;matt@netpoint.be&quot;]
        ///[Country &quot;Japan&quot;]
        ///[Sente &quot;Yonenaga Kunio&quot;]
        ///[Gote &quot;Minami Yoshikazu&quot;]
        ///[Black_grade &quot; &quot;]
        ///[White_grade &quot; &quot;]
        ///[Result &quot; &quot;]
        ///[Comment &quot;Original filename : 40osho1.txt&quot;]
        ///[Source &quot;Reijer Grimbergen&quot;]
        ///[Event &quot;40th Osho Title Match&quot;]
        ///[Date &quot;19910117&quot;]
        ///[Round &quot;1&quot;]
        ///[Venue &quot; &quot;]
        ///[Proam &quot;Professional&quot;]
        ///P7g-7f P8c-8d P2g-2f P8d-8e B8h-7g P3c-3d S7i-8h G4a-3b G6i-7h B2bx7g+ S8hx7g S3a-2b S3i-3h S7a-7b P4g-4f S2b-3c S3h-4g K5a-4b G4i-5h G6a-5b P3g-3f S7b-8c N2i-3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _40th_Osho_Match {
            get {
                return ResourceManager.GetString("_40th_Osho_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name &quot;Matt Casters&quot;]
        ///[Email &quot;matt@netpoint.be&quot;]
        ///[Country &quot;Japan&quot;]
        ///[Sente &quot;Nakahara Makoto&quot;]
        ///[Gote &quot;Tanigawa Koji&quot;]
        ///[Black_grade &quot; &quot;]
        ///[White_grade &quot; &quot;]
        ///[Result &quot; &quot;]
        ///[Comment &quot;Original filename : 48meiji1.txt&quot;]
        ///[Source &quot;Reijer Grimbergen&quot;]
        ///[Event &quot;48th Meijin Title Match&quot;]
        ///[Date &quot;19900412&quot;]
        ///[Round &quot;1&quot;]
        ///[Venue &quot; &quot;]
        ///[Proam &quot;Professional&quot;]
        ///P2g-2f P8c-8d P2f-2e P8d-8e G6i-7h G4a-3b P2e-2d P2cx2d R2hx2d P*2c R2d-2f S7a-7b P1g-1f P1c-1d S3i-3h P9c-9d P9g-9f P3c-3d P7g-7f K5a-4b K5i-5h P8e-8f P8gx8f  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _48th_Meijin_Match {
            get {
                return ResourceManager.GetString("_48th_Meijin_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name &quot;Matt Casters&quot;]
        ///[Email &quot;matt@netpoint.be&quot;]
        ///[Country &quot;Japan&quot;]
        ///[Sente &quot;Nakahara Makoto&quot;]
        ///[Gote &quot;Yonenaga Kunio&quot;]
        ///[Black_grade &quot; &quot;]
        ///[White_grade &quot; &quot;]
        ///[Result &quot; &quot;]
        ///[Comment &quot;Original filename : 49meiji1.txt&quot;]
        ///[Source &quot;Reijer Grimbergen&quot;]
        ///[Event &quot;49th Meijin Title Match&quot;]
        ///[Date &quot;19910410&quot;]
        ///[Round &quot;1&quot;]
        ///[Venue &quot; &quot;]
        ///[Proam &quot;Professional&quot;]
        ///P7g-7f P8c-8d S7i-6h P3c-3d S6h-7g S7a-6b S3i-4h S3a-4b P5g-5f G4a-3b G4i-5h K5a-4a P6g-6f P5c-5d G5h-6g G6a-5b G6i-7h S4b-3c K5i-6i B2b-3a B8h-7i P4c-4d P3g- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _49th_Meijin_Match {
            get {
                return ResourceManager.GetString("_49th_Meijin_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name &quot;Matt Casters&quot;]
        ///[Email &quot;matt@netpoint.be&quot;]
        ///[Country &quot;Japan&quot;]
        ///[Sente &quot;Tanigawa Koji&quot;]
        ///[Gote &quot;Morishita Taku&quot;]
        ///[Black_grade &quot; &quot;]
        ///[White_grade &quot; &quot;]
        ///[Result &quot;Jishogi&quot;]
        ///[Comment &quot;Original filename : 4ryuo1.txt&quot;]
        ///[Source &quot;Reijer Grimbergen&quot;]
        ///[Event &quot;4th Ryu O Tournament&quot;]
        ///[Date &quot;19911024&quot;]
        ///[Round &quot;1&quot;]
        ///[Venue &quot; &quot;]
        ///[Proam &quot;Professional&quot;]
        ///P7g-7f P8c-8d P2g-2f P8d-8e B8h-7g P3c-3d S7i-8h G4a-3b G6i-7h B2bx7g+ S8hx7g S3a-4b S3i-3h S7a-7b P4g-4f P6c-6d S3h-4g S7b-6c P6g-6f P4c-4d G4i-5h G6a-5b K5i- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4th_RyuO_Match {
            get {
                return ResourceManager.GetString("_4th_RyuO_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name &quot;Matt Casters&quot;]
        ///[Email &quot;matt@impakt.be&quot;]
        ///[Country &quot;Japan&quot;]
        ///[Sente &quot;Nakahara Makoto&quot;]
        ///[Gote &quot;Yashiki Nobuyuki&quot;]
        ///[Black_grade &quot;Kisei&quot;]
        ///[White_grade &quot;5dan&quot;]
        ///[Result &quot;1-0&quot;]
        ///[Comment &quot;Suprise victory by Yashiki Nobuyuki (5dan) over Nakahara (9&quot;]
        ///[Source &quot;Shogi-L Archives, Reijer Grimbergen&quot;]
        ///[Event &quot;56th Kisei Title Match 1990&quot;]
        ///[Date &quot;19900618&quot;]
        ///[Round &quot;1&quot;]
        ///[Venue &quot; &quot;]
        ///[Proam &quot;Professional&quot;]
        ///P2g-2f P8c-8d P2f-2e P8d-8e G6i-7h G4a-3b P2e-2d P2cx2d R2hx2d P&apos;2c R2d-2f P9c-9d P1g-1f P1c-1d S3i- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _56th_Kisei_Match {
            get {
                return ResourceManager.GetString("_56th_Kisei_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name &quot;Matt Casters&quot;]
        ///[Email &quot;matt@impakt.be&quot;]
        ///[Country &quot;Japan&quot;]
        ///[Sente &quot;Morishita Taku&quot;]
        ///[Gote &quot;Yashiki Nobuyuki&quot;]
        ///[Black_grade &quot;Chall&quot;]
        ///[White_grade &quot;Kisei&quot;]
        ///[Result &quot;1-0&quot;]
        ///[Comment &quot;Flamboyant &amp; unorthodox style (R.G.)&quot;]
        ///[Source &quot;Shogi-L Archives, Reijer Grimbergen&quot;]
        ///[Event &quot;57th Kisei Title Match 1991&quot;]
        ///[Date &quot;19901211&quot;]
        ///[Round &quot;1&quot;]
        ///[Venue &quot; &quot;]
        ///[Proam &quot;Professional&quot;]
        ///P7g-7f P3c-3d P2g-2f P4c-4d S3i-4h S3a-3b P5g-5f R8b-4b K5i-6h K5a-6b K6h-7h S7a-7b G4i-5h K6b-7a P9g-9f P9c-9d P8g-8f S3b- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _57th_Kisei_Match {
            get {
                return ResourceManager.GetString("_57th_Kisei_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name &quot;Matt Casters&quot;]
        ///[Email &quot;matt@netpoint.be&quot;]
        ///[Country &quot;Japan&quot;]
        ///[Sente &quot;Yashiki Nobuyuki&quot;]
        ///[Gote &quot;Minami Yoshikazu&quot;]
        ///[Black_grade &quot; &quot;]
        ///[White_grade &quot; &quot;]
        ///[Result &quot; &quot;]
        ///[Comment &quot;Original filename : 58kisei1.txt&quot;]
        ///[Source &quot;Reijer Grimbergen&quot;]
        ///[Event &quot;58th Kisei Title Match&quot;]
        ///[Date &quot;19910618&quot;]
        ///[Round &quot;1&quot;]
        ///[Venue &quot; &quot;]
        ///[Proam &quot;Professional&quot;]
        ///P7g-7f P8c-8d S7i-6h P3c-3d S6h-7g S7a-6b P5g-5f P5c-5d S3i-4h S3a-4b G4i-5h G4a-3b P6g-6f K5a-4a G5h-6g P7c-7d G6i-7h G6a-5b B8h-7i S4b-3c K5i-6i B2b-3a B7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _58th_Kisei_Match {
            get {
                return ResourceManager.GetString("_58th_Kisei_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Date &quot;1991/12/10&quot;]
        ///[Event &quot;59th Kisei Title Match&quot;]
        ///[Black &quot;Tanigawa Koji&quot;]
        ///[White &quot;Minami Yoshikazu&quot;]
        ///[Round &quot;1&quot;]
        ///P7g-7f P8c-8d S7i-6h P3c-3d S6h-7g S7a-6b S3i-4h P5c-5d P5g-5f S3a-4b G4i-5h G4a-3b P6g-6f K5a-4a G5h-6g P7c-7d P2g-2f S4b-3c B8h-7i B2b-3a K5i-6h S6b-7c K6h-7h S7c-6d K7h-8h P9c-9d G6i-7h P9d-9e P3g-3f N8a-7c P2f-2e R8b-5b N2i-3g P4c-4d P4g-4f N7c-8e S7g-8f P7d-7e P4f-4e P7ex7f P4ex4d R5b-7b P2e-2d P2cx2d N3g-4e S3cx4d P*4b B3ax4b B7ix2d P*2c B2dx4b+ R7bx4b P6f-6e S4dx4e P6ex6d B*4d S*6f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _59th_Kisei_Match {
            get {
                return ResourceManager.GetString("_59th_Kisei_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[Date &quot;1993/04/12&quot;]
        ///[Event &quot;Meijin-sen&quot;]
        ///[Opening &quot;Aigakari&quot;]
        ///[Black &quot;Nakahara Makoto&quot;]
        ///[White &quot;Yonenaga Kunio&quot;]
        ///1.P2f 	2.P8d 	3.P2e 	4.P8e 	5.G7h 	6.G3b 
        ///7.P2d 	8.Px 	9.Rx 	10.P2c 	11.R2f 	12.S7b 
        ///13.P1f 	14.P1d 	15.S4h 	16.P6d 	17.K6i 	18.P3d 
        ///19.G5i 	20.K4b 	21.P9f 	22.P9d 	23.P7f 	24.P8f 
        ///25.Px 	26.Rx 	27.R5f 	28.R8b 	29.P3f 	30.P4d 
        ///31.N7g 	32.S6c 	33.R5e 	34.G7b 	35.N3g 	36.P7d 
        ///37.P1e 	38.Px 	39.R8e 	40.G8c 	41.P1c 	42.Lx 
        ///43.N2e 	44.P7e 	45.N1c+ 	46.Nx 	47.R7e 	48.G7d 
        ///49.P8c 	50.R7b  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ethalon {
            get {
                return ResourceManager.GetString("ethalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Date &quot;1992/01/16&quot;]
        ///[Event &quot;Osho-sen&quot;]
        ///[Opening &quot;Shikenbisha&quot;]
        ///[Black &quot;Minami Yoshikazu&quot;]
        ///[White &quot;Tanigawa Koji&quot;]
        ///1.P7f 	2.P3d 	3.P2f 	4.P4d 	5.P2e 	6.B3c 
        ///7.S4h 	8.S3b 	9.P5f 	10.R4b 	11.K6h 	12.K6b 
        ///13.K7h 	14.K7b 	15.G45h 	16.K8b 	17.P9f 	18.S4c 
        ///19.S5g 	20.G45b 	21.P8f 	22.P6d 	23.K8g 	24.L9b 
        ///25.S7h 	26.K9a 	27.P3f 	28.S8b 	29.S4f 	30.G7a 
        ///31.P3e 	32.R3b 	33.P3d 	34.Sx 	35.S5e 	36.S4c 
        ///37.P3d 	38.B5a 	39.R3h 	40.P7d 	41.S4d 	42.Sx 
        ///43.Bx 	44.S4i 	45.R3i 	46.S5h+ 	47.Gx 	48.B8d 
        ///49.R3e 	50. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Jan_Jun1992 {
            get {
                return ResourceManager.GetString("Jan_Jun1992", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Sente &quot;Sokei Ohashi&quot;]
        ///[Gote &quot;Honimbo Sansa&quot;]
        ///[Date &quot;1607&quot;]
        ///[Result &quot;1-0&quot;]
        ///[Moves &quot;133&quot;]
        ///{ Here I am with the oldest kifu. Sorry to be late, but I had to learn first how it is to be recorded in the international fashion. Thanks to Matt Leonard&apos;s home page, I managed somehow.
        ///
        ///The players were Ohashi Sokei (black) and Honimbo Sansa (white). Sokei is well-known because of his name, So-Kei,meaning double-Kei(ma). He is said to have shown an artistic touch in his use of Keima, thereby was given the name  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string misc_pro_games {
            get {
                return ResourceManager.GetString("misc_pro_games", resourceCulture);
            }
        }
    }
}
